data:
  raw_path: "data/raw/dataset.csv"
  processed_path: "data/processed/"
  embeddings_path: "data/embeddings/"

model:
  mamba:
    vocab_size: 30000
    d_model: 1024
    n_layers: 6
  rag:
    model_name: "llama3.1"

training:
  batch_size: 32
  epochs: 100
  learning_rate: 5e-5
  

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
